apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: nova-gas
  name: nova-gas
spec:
  storageClassName: "local-storage"
  volumeName: nova-gaspv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
